version: '3'
services:
  admin-db:
    image: docker.io/bitnami/postgresql:14
    container_name: admin-db
    ports:
      - '9449:5432'
    volumes:
      - 'admin_db_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=my_password
      - POSTGRESQL_DATABASE=my_database
      - ALLOW_EMPTY_PASSWORD=yes
volumes:
  admin_db_data:
    driver: local